### ISSUE TITLE
pgmagick throws Symbol not found: __ZN6Magick22DrawableCompositeImage6magickESs

### ISSUE THREAD

**Issue by phoenixbai** [hhatto/homebrew-pgmagick#1]
I follow the installation steps and get pgmagick installed successfully.
Below is the installation log, I am using the python from anaconda 2.7.8 and install the pgmagick under the directory: /Users/phoenix/programs/anaconda/lib/python2.7/site-packages

and my os version is : 

``` bash
phoenix@Phoenix:site-packages$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.1
BuildVersion:   14B25
```

``` bash
creating build/bdist.macosx-10.5-x86_64
creating build/bdist.macosx-10.5-x86_64/egg
creating build/bdist.macosx-10.5-x86_64/egg/pgmagick
copying build/lib.macosx-10.5-x86_64-2.7/pgmagick/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/pgmagick
copying build/lib.macosx-10.5-x86_64-2.7/pgmagick/_pgmagick.so -> build/bdist.macosx-10.5-x86_64/egg/pgmagick
copying build/lib.macosx-10.5-x86_64-2.7/pgmagick/_version.py -> build/bdist.macosx-10.5-x86_64/egg/pgmagick
copying build/lib.macosx-10.5-x86_64-2.7/pgmagick/api.py -> build/bdist.macosx-10.5-x86_64/egg/pgmagick
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pgmagick/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pgmagick/_version.py to _version.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pgmagick/api.py to api.pyc
creating stub loader for pgmagick/_pgmagick.so
byte-compiling build/bdist.macosx-10.5-x86_64/egg/pgmagick/_pgmagick.py to _pgmagick.pyc
creating build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying pgmagick.egg-info/PKG-INFO -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying pgmagick.egg-info/SOURCES.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying pgmagick.egg-info/dependency_links.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying pgmagick.egg-info/top_level.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.5-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/pgmagick-0.5.8-py2.7-macosx-10.5-x86_64.egg' and adding 'build/bdist.macosx-10.5-x86_64/egg' to it
removing 'build/bdist.macosx-10.5-x86_64/egg' (and everything under it)
Processing pgmagick-0.5.8-py2.7-macosx-10.5-x86_64.egg
Copying pgmagick-0.5.8-py2.7-macosx-10.5-x86_64.egg to /Users/phoenix/programs/anaconda/lib/python2.7/site-packages
Adding pgmagick 0.5.8 to easy-install.pth file

Installed /Users/phoenix/programs/anaconda/lib/python2.7/site-packages/pgmagick-0.5.8-py2.7-macosx-10.5-x86_64.egg
Processing dependencies for pgmagick==0.5.8
Finished processing dependencies for pgmagick==0.5.8
==> Cleaning
==> Finishing up
==> Summary
/usr/local/Cellar/pgmagick/0.5.8: 3 files, 12K, built in 4.6 minutes

```

And when I try to import the pgmagick in python console, it throws below error.
I googled, and tried uninstall & install several times, but nothing helps.
So, please, could you tell what went wrong here? How should I correct it?

``` python

phoenix@Phoenix:Formula$ python
Python 2.7.8 |Anaconda 2.1.0 (x86_64)| (default, Aug 21 2014, 15:21:46)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import pgmagick
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.5-x86_64/egg/pgmagick/__init__.py", line 1, in <module>
    #
  File "build/bdist.macosx-10.5-x86_64/egg/pgmagick/_pgmagick.py", line 7, in <module>
  File "build/bdist.macosx-10.5-x86_64/egg/pgmagick/_pgmagick.py", line 6, in __bootstrap__
ImportError: dlopen(/Users/phoenix/.python-eggs/pgmagick-0.5.8-py2.7-macosx-10.5-x86_64.egg-tmp/pgmagick/_pgmagick.so, 2): Symbol not found: __ZN6Magick22DrawableCompositeImage6magickESs
  Referenced from: /Users/phoenix/.python-eggs/pgmagick-0.5.8-py2.7-macosx-10.5-x86_64.egg-tmp/pgmagick/_pgmagick.so
  Expected in: dynamic lookup
```

thanks!

**Comment by LucyWang2014** [comment]
Hi, I have the same problem, is there a solution available? Thanks!

**Comment by hhatto** [comment]
@phoenixbai @lw1582 

Sorry for late reply.

`python` is installed via Homebrew?

After you have re-installed with the latest version, or you tell us the results of executing the following command?

```
# reinstall pgmagick
$ brew untap hhatto/pgmagick
$ brew tap hhatto/pgmagick
$ brew reinstall pgmagick

# show object file info
$ otool -L $PGMAGICK_SO_PATH/_pgmagick.so
```
